import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { beforeAll, describe, expect, it } from 'vitest';
import { juzContaining, juzMatches, juzRangeLabel, setJuzIndex } from '../js/quran-juz.js';

// data/quran/juz.json is generated by tools/build-quran-juz.mjs, which reconciles two independent
// sources before writing. This asserts the property that matters at runtime and that no single
// source can establish on its own: the thirty ajza are a partition of the mushaf this app ships --
// every ayah in exactly one juz, in order, none missing and none counted twice. A boundary that is
// quietly wrong would send someone to the wrong place to start reading, so it is checked here too
// rather than only in the generator that ran once.
const DATA = resolve(process.cwd(), 'data/quran');
const juzFile = JSON.parse(readFileSync(resolve(DATA, 'juz.json'), 'utf8'));
const index = JSON.parse(readFileSync(resolve(DATA, 'index.json'), 'utf8'));
const nameOf = (number) => index.surahs.find((surah) => surah.number === number).nameSimple;

beforeAll(() => setJuzIndex(juzFile));

describe('the thirty ajza', () => {
  it('are thirty, covering the whole mushaf', () => {
    expect(juzFile.totalJuz).toBe(30);
    expect(juzFile.juz).toHaveLength(30);
    expect(juzFile.totalAyahs).toBe(index.totalAyahs);
  });

  it('run from the opening of Al-Fatihah to the end of An-Nas', () => {
    expect(juzFile.juz[0].start).toEqual({ surah: 1, ayah: 1 });
    expect(juzFile.juz[29].end).toEqual({ surah: 114, ayah: 6 });
  });

  it('tile every ayah exactly once, in order', () => {
    const seen = new Map();
    let expected = 0;
    const position = new Map();
    for (const surah of index.surahs) {
      for (let ayah = 1; ayah <= surah.ayahCount; ayah += 1) {
        position.set(`${surah.number}:${ayah}`, position.size);
      }
    }
    for (const juz of juzFile.juz) {
      let counted = 0;
      for (const part of juz.surahs) {
        for (let ayah = part.from; ayah <= part.to; ayah += 1) {
          const key = `${part.surah}:${ayah}`;
          const at = position.get(key);
          expect(at, `${key} is not an ayah of this mushaf`).toBeTypeOf('number');
          expect(seen.has(key), `${key} appears in juz ${seen.get(key)} and juz ${juz.number}`).toBe(false);
          expect(at, `juz ${juz.number} is out of order at ${key}`).toBe(expected);
          seen.set(key, juz.number);
          expected += 1;
          counted += 1;
        }
      }
      expect(counted, `juz ${juz.number} claims ${juz.ayahCount} ayahs`).toBe(juz.ayahCount);
    }
    expect(seen.size).toBe(index.totalAyahs);
  });

  it('add up to 6,236 ayahs', () => {
    const total = juzFile.juz.reduce((sum, juz) => sum + juz.ayahCount, 0);
    expect(total).toBe(6236);
  });
});

describe('finding the juz an ayah is in', () => {
  it('places the ayahs either side of a mid-surah boundary in different ajza', () => {
    // Juz 1 ends at 2:141 and juz 2 begins at 2:142 -- the same surah, two ajza.
    expect(juzContaining(juzFile.juz, 2, 141)).toBe(1);
    expect(juzContaining(juzFile.juz, 2, 142)).toBe(2);
  });

  it('places the first and last ayahs of the mushaf', () => {
    expect(juzContaining(juzFile.juz, 1, 1)).toBe(1);
    expect(juzContaining(juzFile.juz, 114, 6)).toBe(30);
  });

  it('agrees with the tiling for every ayah', () => {
    for (const juz of juzFile.juz) {
      for (const part of juz.surahs) {
        expect(juzContaining(juzFile.juz, part.surah, part.from)).toBe(juz.number);
        expect(juzContaining(juzFile.juz, part.surah, part.to)).toBe(juz.number);
      }
    }
  });

  it('returns null for an ayah no surah has, rather than guessing', () => {
    expect(juzContaining(juzFile.juz, 1, 8)).toBeNull();
    expect(juzContaining(juzFile.juz, 115, 1)).toBeNull();
    expect(juzContaining(undefined, 1, 1)).toBeNull();
  });
});

describe('how a juz reads in the list', () => {
  it('names both ends when a juz spans surahs', () => {
    expect(juzRangeLabel(juzFile.juz[0], nameOf)).toBe('Al-Fatihah 1 \u2013 Al-Baqarah 141');
  });

  it('names the surah once when a juz sits inside one', () => {
    // Juz 2 is entirely within Al-Baqarah.
    expect(juzRangeLabel(juzFile.juz[1], nameOf)).toBe('Al-Baqarah 142 \u2013 252');
  });

  it('is searchable by number and by a surah inside it', () => {
    const juz30 = juzFile.juz[29];
    expect(juzMatches(juz30, '30', nameOf)).toBe(true);
    expect(juzMatches(juz30, 'an-nas', nameOf)).toBe(true);
    expect(juzMatches(juz30, 'al-baqarah', nameOf)).toBe(false);
    expect(juzMatches(juz30, '', nameOf)).toBe(true);
  });
});
