export const state = {
  entries: [],
  filtered: [],
  currentIndex: 0,
  currentPart: 0,
  showFavouritesOnly: false,
  activeQuickFilter: 'all',
  activeMood: '',
  visibleCount: 36,
  favourites: new Set(JSON.parse(localStorage.getItem('favourites') || '[]')),
  fontScale: Number(localStorage.getItem('fontScale') || '1'),
  darkMode: localStorage.getItem('darkMode') === 'true',
  largeArabic: localStorage.getItem('largeArabic') === 'true',
  advancedUi: localStorage.getItem('advancedUi') === 'true',
  advancedListMode: false,
  advancedFilter: 'all',
  deferredInstallPrompt: null,
  waitingWorker: null,
  refreshing: false,
  contentMode: 'duas',
  quranSurah: null,
  lastWorshipMode: 'prayerTimes',
  calculationMethod: localStorage.getItem('calculationMethod') || 'mwl',
  asrMethod: localStorage.getItem('asrMethod') || 'standard',
  manualLatitude: localStorage.getItem('manualLatitude') ? Number(localStorage.getItem('manualLatitude')) : null,
  manualLongitude: localStorage.getItem('manualLongitude') ? Number(localStorage.getItem('manualLongitude')) : null,
  lastKnownLatitude: localStorage.getItem('lastKnownLatitude') ? Number(localStorage.getItem('lastKnownLatitude')) : null,
  lastKnownLongitude: localStorage.getItem('lastKnownLongitude') ? Number(localStorage.getItem('lastKnownLongitude')) : null,
  prayerTimes: null,
  prayerCountdownTimer: null,
  deviceOrientationActive: false,
  remindersEnabled: localStorage.getItem('remindersEnabled') === 'true',
  morningAdhkarEnabled: localStorage.getItem('morningAdhkarEnabled') !== 'false',
  eveningAdhkarEnabled: localStorage.getItem('eveningAdhkarEnabled') !== 'false',
};
